-- Chercher les demandes qui ont été faites après une date donnée. (ici 04/10/2018)
SELECT *
FROM DEMANDE
WHERE DATEDEMANDE >= TO_DATE('2018-10-04', 'yyyy/mm/dd');

-- Pour une demande donnée, afficher la raison sociale de l’entreprise, la tournée correspondante et la quantité
-- à récupérer pour chaque type de déchet. (ici demande n°56)

SELECT E.RAISONSOCIALE, T.*, TYPED.NOMTYPEDECHET, DETAILDEM.QUANTITEENLEVEE
FROM DEMANDE D
    JOIN ENTREPRISE E on D.SIRET = E.SIRET
    JOIN TOURNEE T on D.NOTOURNEE = T.NOTOURNEE
    JOIN DETAILDEMANDE DETAILDEM on D.NODEMANDE = DETAILDEM.NODEMANDE
    JOIN TYPEDECHET TYPED on DETAILDEM.NOTYPEDECHET = TYPED.NOTYPEDECHET
WHERE D.NODEMANDE = 56;

-- Afficher la quantité totale récupérée par type de déchet pour un mois/année donné.
-- (ici septembre 2018)

SELECT DETAILDEMANDE.NOTYPEDECHET, TYPEDECHET.NOMTYPEDECHET, SUM(QUANTITEENLEVEE) AS QUANTITETOTALE
FROM DETAILDEMANDE
    JOIN DEMANDE ON DETAILDEMANDE.NODEMANDE = DEMANDE.NODEMANDE
    JOIN TYPEDECHET ON DETAILDEMANDE.NOTYPEDECHET = TYPEDECHET.NOTYPEDECHET
WHERE DETAILDEMANDE.NODEMANDE = DEMANDE.NODEMANDE
AND EXTRACT( YEAR FROM DATEENLEVEMENT) = 2018
AND EXTRACT( MONTH FROM DATEENLEVEMENT) = 9
GROUP BY DETAILDEMANDE.NOTYPEDECHET, TYPEDECHET.NOMTYPEDECHET
ORDER BY DETAILDEMANDE.NOTYPEDECHET;

-- Afficher les employés ayant réalisé moins de n tournées. Triez le résultat sur le nombre de tournées.
-- (ici moins de 5 tournées)

SELECT E.NOEMPLOYE, E.NOM, E.PRENOM, COUNT(*) AS NBTOURNEES
FROM TOURNEE T JOIN
    EMPLOYE E on T.NOEMPLOYE = E.NOEMPLOYE
GROUP BY E.NOEMPLOYE, E.NOM, E.PRENOM
HAVING COUNT(*) < 5
ORDER BY NBTOURNEES DESC;

-- Affichez les informations de l’entreprise qui a réalisé plus de demandes que l’entreprise Formalys

SELECT ENTREPRISE.SIRET, RAISONSOCIALE, NORUEENTR, RUEENTR, CPOSTALENTR, VILLEENTR, NOTEL, CONTACT, COUNT(NODEMANDE) AS DEMANDESREALISEES
FROM DEMANDE
    JOIN ENTREPRISE on DEMANDE.SIRET = ENTREPRISE.SIRET
WHERE DEMANDE.SIRET = ENTREPRISE.SIRET
GROUP BY DEMANDE.SIRET, ENTREPRISE.SIRET, RAISONSOCIALE, NORUEENTR, RUEENTR, CPOSTALENTR, VILLEENTR, NOTEL, CONTACT
HAVING COUNT(DATEDEMANDE) > (   SELECT COUNT(NODEMANDE) FROM ENTREPRISE, DEMANDE
                                    WHERE ENTREPRISE.SIRET = DEMANDE.SIRET
                                    AND ENTREPRISE.RAISONSOCIALE = 'Formalys')
ORDER BY DEMANDESREALISEES DESC;

-- Affichez les informations des demandes qui ne sont pas encore inscrites dans une tournée.

SELECT D.NODEMANDE, D.DATEDEMANDE, D.DATEENLEVEMENT, D.WEB_O_N, D2.QUANTITEENLEVEE, D2.REMARQUE
FROM DEMANDE D
    LEFT JOIN DETAILDEMANDE D2 on D.NODEMANDE = D2.NODEMANDE
WHERE D.NOTOURNEE is NULL;
