-- Ficher à exécuter en tant que SYSDBA pour supprimer l'ensemble des utilisateurs
-- créés via le script de l'exercice n°4

DROP USER E_DBRI CASCADE;
DROP USER E_MVAN CASCADE;
DROP USER E_MMAR CASCADE;
DROP USER E_VIDE CASCADE;
DROP USER A_LDEC CASCADE;
DROP USER D_DAND CASCADE;
DROP USER E_JVER CASCADE;
DROP USER E_MDUP CASCADE;
DROP USER E_ALAR CASCADE;
DROP USER A_JZEV CASCADE;
DROP USER E_DRAN CASCADE;
DROP USER E_MDEL CASCADE;
DROP USER D_DSIM CASCADE;
DROP USER E_MAND CASCADE;