-- ==============
-- Suppression de l'utilisateur & tablespace (SYSDBA only, attention les données sont supprimées)
-- ==============

drop tablespace rfrance_tablespace including contents;
drop tablespace rfrance_tablespace_temp including contents;
drop user rfrance;


-- ==============
-- Suppression des tables et séquences
-- ==============

-- /////////////////////////////////////////////////////
-- / Début des actions à exécuter pour la restauration /
-- /////////////////////////////////////////////////////

DROP SEQUENCE SEQ_SITE;
DROP SEQUENCE SEQ_CENTRE;
DROP SEQUENCE SEQ_DEMANDE;
DROP SEQUENCE SEQ_EMPLOYE;
DROP SEQUENCE SEQ_TOURNEE;
DROP SEQUENCE SEQ_TYPEDECHET;

DROP TABLE DETAILDEPOT;
DROP TABLE DETAILDEMANDE;
DROP TABLE DEMANDENONTRAITEE;
DROP TABLE DEMANDE;
DROP TABLE TOURNEE;
DROP TABLE CAMION;
DROP TABLE EMPLOYE;
DROP TABLE SITE;
DROP TABLE TYPEDECHET;
DROP TABLE FONCTION;
DROP TABLE CENTRETRAITEMENT;
DROP TABLE ENTREPRISE;

-- ==============
-- Suppression des procédures, fonctions, triggers et vues
-- ==============
DROP VIEW NB_DEMANDES_AFFECTEES_TOURNEE;
DROP VIEW TOURNEES_DISPONIBLES;
DROP VIEW EMPLOYES_SITE;
DROP VIEW CAMIONS_SITE;
DROP VIEW DEMANDES_SITE;
DROP VIEW DEMANDES_NON_TRAITEES_SITE;
DROP VIEW TOURNEES_SITE;
DROP VIEW DETAIL_DEMANDES_SITE;
DROP VIEW DETAIL_DEPOTS_SITE;
DROP VIEW TOURNEES_EMPLOYE;
DROP VIEW DEMANDES_EMPLOYE;
DROP VIEW DETAIL_DEMANDES_EMPLOYE;
DROP VIEW DETAIL_DEPOTS_EMPLOYE;

DROP PROCEDURE AFFECTATION_DEMANDE_TOURNEE;
DROP PROCEDURE AFFICHE_AFFECTATION;
DROP PROCEDURE AFFICHE_ECHEC_AFFECTATION;
DROP PROCEDURE INSCRIPTION_DEMANDES_TOURNEES;
DROP PROCEDURE DEPLACEMENT_DEMANDE_VERS_DEMANDE_NON_TRAITEE;

DROP FUNCTION QUANTITE_TYPEDECHET_SITE_PERIODE;
DROP FUNCTION QUANTITE_TYPEDECHET_NATIONAL_PERIODE;
DROP FUNCTION NOMBRE_TOURNEES_DISPONIBLES;
DROP FUNCTION QUANTITE_ENLEVEE_TYPE_TOURNEE;
DROP FUNCTION QUANTITE_RESTANTE_A_DEPOSER_TYPE_TOURNEE;

-- ///////////////////////////////////////////////////
-- / Fin des actions à exécuter pour la restauration /
-- ///////////////////////////////////////////////////

DROP TRIGGER VERIF_QTE_DEPOSEE;
DROP TRIGGER NOT_EDITABLE_USERNAME;
DROP TRIGGER VERIF_CAMION_EMPLOYEE_SITE;
DROP TRIGGER VERIF_AFFECTATION_TOURNEE_SITE;
DROP TRIGGER VERIF_DEMANDE_TOURNEE_EMPLOYE;
DROP TRIGGER VERIF_DEPOT_TOURNEE_EMPLOYE;