DROP SEQUENCE SEQ_CENTRE;
DROP SEQUENCE SEQ_DEMANDE;
DROP SEQUENCE SEQ_EMPLOYE;
DROP SEQUENCE SEQ_TOURNEE;
DROP SEQUENCE SEQ_TYPEDECHET;

DROP TABLE DETAILDEPOT;
DROP TABLE DETAILDEMANDE;
DROP TABLE DEMANDE;
DROP TABLE TOURNEE;
DROP TABLE CAMION;
DROP TABLE TYPEDECHET;
DROP TABLE EMPLOYE;
DROP TABLE CENTRETRAITEMENT;
DROP TABLE ENTREPRISE;